### ISSUE TITLE
求助！

### ISSUE THREAD

**Issue by kaze-kaze** [anhao/TgMessage#1]
你好，请问最后一步设置 WebHook能不能写的详细一点？请问在哪里执行执行 `curl以及php 执行 set webhook 脚本？谢谢！

**Comment by anhao** [comment]
curl 脚本改一下token 以及 部署的域名，然后复制到 linux 服务器执行就可以.

php 的话，你本地能运行php脚本的话，改一下token以及域名，直接执行 php 脚本就可以。
比如新建一个 ` test.php ` 文件，然后直接运行 `php test.php`

**Comment by anhao** [comment]
也可以下载一个 postman , 然后复制 curl 导入进去

![image](https://user-images.githubusercontent.com/9844218/107378542-07947b00-6b27-11eb-8b54-27197ba365a5.png)

**Comment by anhao** [comment]
https://github.com/anhao/TgMessage#%E9%83%A8%E7%BD%B2%E5%88%B0-vercel

**Comment by kaze-kaze** [comment]
感谢！
