### ISSUE TITLE
你好！请问key填写什么内容？

### ISSUE THREAD

**Issue by pengliansheng** [anhao/TgMessage#2]
请问最后一步当中的环境变量key: 设置 webhook 的请求参数 时设置什么内容？翻遍全文没找到解释........

**Comment by anhao** [comment]
key 就是访问 /setWebhook 是的 key 参数

**Comment by pengliansheng** [comment]
你可能高估了小白的理解能力......咋访问setwebhook啊......访问啥setwebhook？

**Comment by anhao** [comment]
https://github.com/anhao/TgMessage#%E8%AE%BE%E7%BD%AE%E5%9B%9E%E8%B0%83
